# Generated by Django 4.2.30 on 2026-06-16 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=10, unique=True)),
                ('group', models.CharField(choices=[('economy', 'Ekonomi'), ('mid', 'Orta Sınıf'), ('suv', 'SUV')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Müsait'), ('maintenance', 'Bakımda'), ('service', 'Serviste'), ('inactive', 'Pasif')], default='available', max_length=20)),
                ('total_reservations', models.IntegerField(default=0)),
                ('total_km', models.IntegerField(default=0)),
                ('maintenance_due', models.BooleanField(default=False)),
                ('maintenance_start_date', models.DateField(blank=True, null=True)),
                ('maintenance_end_date', models.DateField(blank=True, null=True)),
                ('service_start_date', models.DateField(blank=True, null=True)),
                ('service_end_date', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.branch')),
            ],
        ),
        migrations.CreateModel(
            name='TransferCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='vehicles.branch')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='vehicles.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(max_length=10, unique=True)),
                ('vehicle_group', models.CharField(choices=[('economy', 'Ekonomi'), ('mid', 'Orta Sınıf'), ('suv', 'SUV')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='vehicles.branch')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('km_at_maintenance', models.IntegerField()),
                ('reservations_at_maintenance', models.IntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='vehicles.reservation')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='vehicles.vehicle')),
            ],
        ),
    ]
