# Generated by Django 4.2.30 on 2026-06-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='km_driven',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
