# Generated by Django 4.2.30 on 2026-06-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_penaltyconfig_reservation_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
