# Generated by Django 4.2.30 on 2026-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_add_branch_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationrun',
            name='unassigned_reservations',
            field=models.ManyToManyField(blank=True, related_name='missed_in_runs', to='vehicles.reservation'),
        ),
    ]
