# Generated by Django 4.2.30 on 2026-06-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicle_brand_alter_vehicle_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='sasi',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
