# Generated by Django 4.2.30 on 2026-06-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehicle_sasi_alter_vehicle_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='vehicles.branch'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Müşteri'), ('representative', 'Temsilci'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sasi',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
