# Generated by Django 4.2.30 on 2026-06-24 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_alter_customerprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='return_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_reservations', to='vehicles.branch'),
        ),
    ]
