# Generated by Django 4.2.30 on 2026-06-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_reservation_return_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Müsait'), ('maintenance', 'Bakımda'), ('service', 'Serviste'), ('inactive', 'Pasif'), ('reserved', 'Rezerve Edildi')], default='available', max_length=20),
        ),
    ]
