# Generated by Django 4.2.30 on 2026-06-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_reservation_guest_email_reservation_guest_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('delivered', 'Teslim Edildi'), ('returned', 'İade Alındı')], max_length=20)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='vehicles.reservation')),
            ],
            options={
                'unique_together': {('reservation', 'event_type')},
            },
        ),
    ]
