# Generated by Django 4.2.30 on 2026-06-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_deliverylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancelog',
            old_name='km_at_maintenance',
            new_name='current_km',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='reservations_at_maintenance',
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='start_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='reason',
            field=models.CharField(choices=[('routine', 'Rutin Bakım'), ('cleaning', 'Temizlik'), ('repair', 'Hasar Onarım')], max_length=50),
        ),
    ]
