# Generated by Django 4.2.30 on 2026-06-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_rename_km_at_maintenance_maintenancelog_current_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vehicle_group', models.CharField(choices=[('economy', 'Ekonomi'), ('mid', 'Orta Sınıf'), ('suv', 'SUV')], max_length=20)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('date', 'vehicle_group')},
            },
        ),
    ]
