# Generated by Django 4.2.30 on 2026-06-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_reservation_total_price_dailyprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='delivery_docs/'),
        ),
    ]
