# Generated by Django 4.2.30 on 2026-06-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_deliverylog_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='damage_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='delivery_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='fuel_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
