# Generated by Django 4.2.30 on 2026-07-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_deliverylog_damage_items_deliverylog_delivery_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='damage_map',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
