# Generated by Django 4.2.30 on 2026-07-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_vehicle_damage_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_photos/'),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='stage',
            field=models.CharField(choices=[('pending', 'Belge Bekleniyor'), ('photo_pending', 'Fotoğraf Bekleniyor'), ('approved', 'Onaylandı')], default='approved', max_length=20),
        ),
    ]
