# Generated by Django 4.2.30 on 2026-07-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0019_deliverylog_photo_deliverylog_stage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['vehicle', 'end_date'], name='vehicles_ma_vehicle_94f452_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='vehicles_re_status_a26e9b_idx'),
        ),
    ]
