# Generated by Django 4.2.30 on 2026-07-03 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0020_maintenancelog_vehicles_ma_vehicle_94f452_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20)),
                ('extra_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='vehicles.reservation')),
            ],
        ),
    ]
