# Generated by Django 4.2.30 on 2026-07-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_reservationextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='billing_city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='billing_country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='billing_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
