# Generated by Django 4.2.30 on 2026-07-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_customerprofile_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='billing_country',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='billing_district',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='billing_tax_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='billing_tax_office',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='billing_tckn',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('bireysel', 'Bireysel'), ('kurumsal', 'Kurumsal')], default='bireysel', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_district',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_tax_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_tax_office',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_tckn',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('bireysel', 'Bireysel'), ('kurumsal', 'Kurumsal')], default='bireysel', max_length=20),
        ),
    ]
