# Generated by Django 4.2.30 on 2026-07-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0023_remove_customerprofile_billing_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='billing_neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
