# Generated by Django 4.2.30 on 2026-07-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0026_notification'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='reservation_end_date_gte_start_date'),
        ),
    ]
