# Generated by Django 4.2.30 on 2026-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0028_alter_reservation_options_reservation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='manually_locked',
            field=models.BooleanField(default=False),
        ),
    ]
