# Generated by Django 4.2.30 on 2026-07-08 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0029_reservation_manually_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('group', models.CharField(choices=[('economy', 'Ekonomi'), ('mid', 'Orta Sınıf'), ('suv', 'SUV')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('benzin', 'Benzin'), ('dizel', 'Dizel'), ('hibrit', 'Hibrit'), ('elektrik', 'Elektrik')], max_length=20)),
                ('transmission', models.CharField(choices=[('manuel', 'Manuel'), ('otomatik', 'Otomatik')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_models/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('brand', 'model', 'fuel_type', 'transmission')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='preferred_vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='vehicles.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.vehiclemodel'),
        ),
    ]
