# Generated by Django 4.2.30 on 2026-07-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0031_dailyprice_vehicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='body_type',
            field=models.CharField(choices=[('B', '2 Kapılı'), ('C', '2/4 Kapılı'), ('D', '4 Kapılı'), ('W', 'Wagon'), ('V', 'Minivan'), ('S', 'SUV'), ('T', 'Kamyonet')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='has_ac',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='is_4wd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='vehicle_group',
            field=models.CharField(choices=[('M', 'Mini'), ('E', 'Ekonomi'), ('C', 'Kompakt'), ('I', 'Orta'), ('S', 'Standart'), ('F', 'Tam Boyut'), ('P', 'Premium'), ('L', 'Lüks'), ('X', 'Özel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='group',
            field=models.CharField(choices=[('M', 'Mini'), ('E', 'Ekonomi'), ('C', 'Kompakt'), ('I', 'Orta'), ('S', 'Standart'), ('F', 'Tam Boyut'), ('P', 'Premium'), ('L', 'Lüks'), ('X', 'Özel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='group',
            field=models.CharField(choices=[('M', 'Mini'), ('E', 'Ekonomi'), ('C', 'Kompakt'), ('I', 'Orta'), ('S', 'Standart'), ('F', 'Tam Boyut'), ('P', 'Premium'), ('L', 'Lüks'), ('X', 'Özel')], max_length=20),
        ),
    ]
