# Generated by Django 4.2.30 on 2026-07-09 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0032_vehiclemodel_body_type_vehiclemodel_has_ac_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='reservation_end_date_gte_start_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date')), models.Q(('end_date', models.F('start_date')), ('end_time__gt', models.F('start_time'))), _connector='OR'), name='reservation_end_after_start'),
        ),
    ]
