# Generated by Django 4.2.30 on 2026-07-10 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0033_reservation_start_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTypeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_kodu', models.IntegerField()),
                ('tip_kodu', models.IntegerField()),
                ('marka_adi', models.CharField(max_length=50)),
                ('tip_adi', models.CharField(max_length=150)),
            ],
            options={
                'indexes': [models.Index(fields=['marka_adi'], name='vehicles_ve_marka_a_70eddd_idx')],
                'unique_together': {('marka_kodu', 'tip_kodu')},
            },
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='type_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_models', to='vehicles.vehicletypecode'),
        ),
    ]
