# Generated by Django 4.2.30 on 2026-07-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0034_vehicletypecode_vehiclemodel_type_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletypecode',
            name='ilk_yil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicletypecode',
            name='son_yil',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
